'use client';

import React, { useState } from 'react';
import { ClientSidebar } from '@/components/ClientSidebar';
import { Receipt, Printer, ShieldAlert, CheckCircle2, Lock } from 'lucide-react';

export default function ClientMyReceiptsPage() {
  const [receipts] = useState([
    {
      id: 'r1',
      receiptNumber: 'REC-2026-0001',
      amount: 450.0,
      currency: 'EUR',
      paymentMethod: 'BANK_TRANSFER',
      paymentDate: '2026-08-01',
      createdByName: 'Sofia Bianchi',
      legalDisclaimer: 'Le montant versé est non remboursable, quels que soient les résultats ou décisions des organismes concernés.',
    },
  ]);

  const totalPaid = receipts.reduce((acc, r) => acc + r.amount, 0);

  return (
    <div className="flex min-h-screen bg-slate-100" id="client-receipts-root">
      <ClientSidebar />
      <main className="flex-1 p-8 space-y-8">
        {/* Header */}
        <div className="flex justify-between items-center">
          <div>
            <h1 className="text-2xl font-extrabold text-slate-900 font-outfit">My Payment Receipts</h1>
            <p className="text-xs text-slate-500 mt-1">Official proof of payments for your ViaItalia application packages</p>
          </div>
          <div className="flex items-center space-x-2 text-xs font-bold text-slate-500 bg-slate-200/60 px-3 py-1.5 rounded-lg">
            <Lock size={14} className="text-slate-600" />
            <span>Client Read-Only View</span>
          </div>
        </div>

        {/* Overview Stats */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
          <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm flex items-center justify-between">
            <div>
              <div className="text-xs font-bold uppercase tracking-wider text-slate-400 font-outfit">Total Amount Paid</div>
              <div className="text-3xl font-extrabold text-emerald-800 font-outfit mt-1">€{totalPaid.toFixed(2)}</div>
            </div>
            <div className="w-12 h-12 rounded-xl bg-emerald-50 text-emerald-700 flex items-center justify-center font-bold">€</div>
          </div>

          <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm flex items-center justify-between">
            <div>
              <div className="text-xs font-bold uppercase tracking-wider text-slate-400 font-outfit">Total Receipts Issued</div>
              <div className="text-3xl font-extrabold text-slate-900 font-outfit mt-1">{receipts.length}</div>
            </div>
            <div className="w-12 h-12 rounded-xl bg-blue-50 text-blue-700 flex items-center justify-center font-bold"><Receipt size={24} /></div>
          </div>
        </div>

        {/* Read-Only Notice */}
        <div className="p-4 bg-slate-200/60 border border-slate-300 rounded-xl text-xs text-slate-700 flex items-start space-x-3">
          <ShieldAlert size={18} className="text-slate-600 shrink-0 mt-0.5" />
          <div>
            <strong>Read-Only Notice:</strong> Receipts are official tax and accounting documents generated by ViaItalia after payment. Clients cannot modify, delete, or edit payment information.
          </div>
        </div>

        {/* Receipts History Table */}
        <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
          <div className="p-6 border-b border-slate-100">
            <h3 className="font-bold text-slate-900 font-outfit text-base">Receipt History</h3>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse" id="client-receipts-table">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-200 text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                  <th className="p-4">Receipt Number</th>
                  <th className="p-4">Payment Date</th>
                  <th className="p-4">Amount Paid</th>
                  <th className="p-4">Payment Method</th>
                  <th className="p-4 text-right">Official Document</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 text-xs">
                {receipts.map((r) => (
                  <tr key={r.id} className="hover:bg-slate-50/80 transition-colors">
                    <td className="p-4 font-bold text-brand-900 font-mono">{r.receiptNumber}</td>
                    <td className="p-4 text-slate-600 font-medium">{r.paymentDate}</td>
                    <td className="p-4 font-extrabold text-emerald-800">€{r.amount.toFixed(2)} {r.currency}</td>
                    <td className="p-4">
                      <span className="px-2.5 py-1 rounded-full text-[10px] font-bold bg-slate-100 text-slate-700 border border-slate-200">
                        {r.paymentMethod === 'BANK_TRANSFER' ? 'Virement (Bank Transfer)' : 'Espèce (Cash)'}
                      </span>
                    </td>
                    <td className="p-4 text-right">
                      <a
                        href={`http://localhost:4000/api/v1/finance/receipts/${r.id}/pdf`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="inline-flex items-center space-x-1.5 px-3 py-1.5 bg-brand-900 hover:bg-brand-800 text-white font-bold rounded-lg text-xs transition-all shadow-sm"
                        id={`btn-client-download-pdf-${r.receiptNumber}`}
                      >
                        <Printer size={14} />
                        <span>View / Download A4 PDF</span>
                      </a>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </main>
    </div>
  );
}
